# Generated by Django 6.0.3 on 2026-03-23 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, null=True)),
                ('is_intelligent', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('visibility', 'Public')), fields=['visibility'], name='visible_playlists'), models.Index(condition=models.Q(('is_intelligent', True)), fields=['is_intelligent'], name='intelligent_playlists')],
            },
        ),
    ]
