# Generated by Django 5.0.4 on 2024-06-18 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychannel', '0004_alter_userchannel_category'),
        ('videos', '0003_remove_video_videos_vide_title_dd8d3a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='video',
            name='active_and_visible_videos',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Film and animation', 'Film And Animation'), ('Music', 'Music'), ('Gaming', 'Gaming'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty')], default='Entertainment', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='comment_strategy',
            field=models.CharField(choices=[('Allow all comments', 'Allow All Comments'), ('Hold all comments for review', 'Hold For Review'), ('Disable all comments', 'Disable All')], default='Allow all comments', max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='recording_language',
            field=models.CharField(choices=[('French', 'French'), ('English', 'English')], default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='viewingprofile',
            name='account_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Artist', 'Artist'), ('Professionnal', 'Professionnal'), ('Corporate', 'Corporate')], default='Basic', max_length=100),
        ),
        migrations.AlterField(
            model_name='viewingprofile',
            name='performance',
            field=models.CharField(choices=[('Auto', 'Auto'), ('1080p', 'P1080'), ('720p', 'P720')], default='Auto', max_length=100),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(condition=models.Q(('visibility', True), ('active', True)), fields=['active', 'visibility'], name='active_and_visible_videos'),
        ),
    ]
