# Generated by Django 6.0 on 2025-12-12 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(max_length=255, unique=True)),
                (
                    "source_credibility",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Credibility score of the source, from 0 to 100",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100)),
                (
                    "creator_id",
                    models.CharField(
                        help_text="Unique identifier for the content creator on whom the note is written",
                        max_length=100,
                    ),
                ),
                ("votes", models.PositiveIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "writer_id",
                    models.ForeignKey(
                        help_text="User who wrote the note",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note_sources",
                    models.ManyToManyField(
                        help_text="Sources that support the note",
                        related_name="notes",
                        to="community_notes.source",
                    ),
                ),
            ],
        ),
    ]
