# Generated by Django 6.0 on 2025-12-13 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Source",
            new_name="CommunityNoteSource",
        ),
        migrations.CreateModel(
            name="CommunityNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the community note", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Content of the community note", max_length=2000
                    ),
                ),
                (
                    "subject_creator_id",
                    models.CharField(
                        help_text="Unique identifier of the content creator this note is about",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                        ],
                        default="draft",
                        help_text="Current status of the community note",
                        max_length=20,
                    ),
                ),
                ("upvotes", models.PositiveIntegerField(default=0)),
                ("downvotes", models.PositiveIntegerField(default=0)),
                ("score", models.IntegerField(db_index=True, default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who authored the note",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note_sources",
                    models.ManyToManyField(
                        help_text="Sources that support the note",
                        related_name="notes",
                        to="community_notes.communitynotesource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunityNoteVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(choices=[(1, "Upvote"), (-1, "Downvote")]),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="community_notes.communitynote",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.AddIndex(
            model_name="communitynote",
            index=models.Index(
                fields=["status", "score"], name="community_n_status_6ba8eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitynote",
            index=models.Index(
                fields=["subject_creator_id", "status"],
                name="community_n_subject_6f9342_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="communitynote",
            index=models.Index(
                fields=["created_on"], name="community_n_created_5296cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitynotevote",
            index=models.Index(
                fields=["note", "value"], name="community_n_note_id_c950ac_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitynotevote",
            unique_together={("note", "user")},
        ),
    ]
