# Generated by Django 6.0 on 2025-12-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "community_notes",
            "0002_rename_source_communitynotesource_communitynote_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="communitynotevote",
            name="reason",
            field=models.CharField(
                blank=True,
                help_text="Optional reason applied only for downvotes",
                max_length=255,
                null=True,
            ),
        ),
    ]
