# Generated by Django 5.0.6 on 2024-10-18 21:57

import accounts.utils
import accounts.validators
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.BooleanField(default=True)),
                ('dating', models.BooleanField(default=True)),
                ('gambling', models.BooleanField(default=True)),
                ('pregnancy_parenting', models.BooleanField(default=True)),
                ('weight_loss', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.utils.avatar_path, validators=[accounts.validators.avatar_extension_validator])),
                ('customer_id', models.CharField(blank=True, help_text='Stripe customer ID', max_length=100, null=True)),
                ('birthdate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription', models.CharField(choices=[(1, 'Free'), (2, 'My Video Plus'), (3, 'My Video Plus Plus')], default=1, max_length=100)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('is_professional', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Basic', 'Basic'), ('Artist', 'Artist'), ('Professionnal', 'Professionnal'), ('Corporate', 'Corporate')], default='Basic', max_length=100)),
                ('night_mode', models.BooleanField(default=False)),
                ('algorithm_decides', models.BooleanField(default=False, help_text='Lets the algorithm decide relevant videos')),
                ('recommend_popular_videos', models.BooleanField(default=False, help_text='Recommend popular videos based on viewing history and currently viewed video')),
                ('performance', models.CharField(choices=[('Auto', 'Auto'), ('1080p', 'P1080'), ('720p', 'P720')], default='Auto', max_length=100)),
                ('blocked_keywords', models.JSONField(blank=True, null=True)),
                ('playlists_private', models.BooleanField(default=False)),
                ('subscriptions_private', models.BooleanField(default=False)),
                ('personalize_ads', models.BooleanField(default=False)),
                ('preferred_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_ad', to='accounts.preferredad')),
                ('preferred_categories', models.ManyToManyField(blank=True, help_text='Categories the user prefers to watch', related_name='preferred_categories', to='accounts.preferredcategory')),
                ('subscriptions', models.ManyToManyField(blank=True, to='accounts.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='active_accounts'),
        ),
        migrations.AddConstraint(
            model_name='activationtoken',
            constraint=models.UniqueConstraint(fields=('token', 'user'), name='one_token_per_user'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(condition=models.Q(('is_professional', True)), fields=['is_professional'], name='pro_accounts'),
        ),
        migrations.AddConstraint(
            model_name='viewingprofile',
            constraint=models.UniqueConstraint(fields=('user', 'preferred_ad'), name='one_preferred_ad_by_user'),
        ),
    ]
