# Generated by Django 5.0.6 on 2024-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingprofile',
            name='account_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Artist', 'Artist'), ('Professionnal', 'Professionnal'), ('Corporate', 'Corporate')], default='Basic', max_length=100),
        ),
        migrations.AlterField(
            model_name='viewingprofile',
            name='performance',
            field=models.CharField(choices=[('Auto', 'Auto'), ('1080p', 'P1080'), ('720p', 'P720')], default='Auto', max_length=100),
        ),
    ]
