# Generated by Django 5.1.4 on 2025-03-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_viewingprofile_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingprofile',
            name='account_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Artist', 'Artist'), ('Professionnal', 'Professionnal'), ('Corporate', 'Corporate')], default='Basic', max_length=100),
        ),
        migrations.AlterField(
            model_name='viewingprofile',
            name='performance',
            field=models.CharField(choices=[('Auto', 'Auto'), ('1080p', 'P1080'), ('720p', 'P720')], default='Auto', max_length=100),
        ),
    ]
