# Generated by Django 3.1.1 on 2020-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychannel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannel',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Commentary', 'Commentary'), ('Corporate', 'Corporate'), ('Other', 'Other')], default='Beauty', max_length=100),
        ),
        migrations.AlterField(
            model_name='userchannel',
            name='reference',
            field=models.CharField(default='23d6f296e4', max_length=50, unique=True),
        ),
    ]
