# Generated by Django 4.1.3 on 2022-11-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychannel', '0002_alter_userchannel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannel',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Commentary', 'Commentary'), ('Corporate', 'Corporate'), ('Other', 'Other')], default='Beauty', max_length=100),
        ),
        migrations.AlterField(
            model_name='userchannel',
            name='reference',
            field=models.CharField(default='d098944908', max_length=50, unique=True),
        ),
    ]
