# Generated by Django 5.0.4 on 2024-06-18 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychannel', '0004_alter_userchannel_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userchannel',
            name='mychannel_u_name_1bb156_idx',
        ),
        migrations.AlterField(
            model_name='userchannel',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Commentary', 'Commentary'), ('Corporate', 'Corporate'), ('Other', 'Other')], default='Beauty', max_length=100),
        ),
        migrations.AddIndex(
            model_name='userchannel',
            index=models.Index(condition=models.Q(('is_verified', True)), fields=['is_verified'], name='verified_channel'),
        ),
    ]
