# Generated by Django 5.0.4 on 2024-06-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychannel', '0005_remove_userchannel_mychannel_u_name_1bb156_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannel',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Commentary', 'Commentary'), ('Corporate', 'Corporate'), ('Other', 'Other')], default='Beauty', max_length=100),
        ),
    ]
