# Generated by Django 3.1.1 on 2020-12-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychannel', '0005_auto_20201220_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannel',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Commentary', 'Commentary'), ('Corporate', 'Corporate'), ('Other', 'Other')], default='Beauty', max_length=100),
        ),
        migrations.AlterField(
            model_name='userchannel',
            name='reference',
            field=models.CharField(default='ce5204c36f', max_length=50, unique=True),
        ),
    ]
