# Generated by Django 4.1 on 2022-08-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychannel', '0006_auto_20201220_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannel',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Commentary', 'Commentary'), ('Corporate', 'Corporate'), ('Other', 'Other')], default='Beauty', max_length=100),
        ),
        migrations.AlterField(
            model_name='userchannel',
            name='reference',
            field=models.CharField(default='1a6af32d0e', max_length=50, unique=True),
        ),
    ]
