# Generated by Django 5.0.6 on 2024-07-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychannel', '0008_alter_userchannel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannel',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Commentary', 'Commentary'), ('Corporate', 'Corporate'), ('Other', 'Other')], default='Beauty', max_length=100),
        ),
    ]
