# Generated by Django 6.0 on 2025-12-12 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(max_length=255, unique=True)),
                (
                    "source_credibility",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Credibility score of the source, from 0 to 100",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=255)),
                ("video_id", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created the report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        related_name="reports", to="factchecking.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="factchecking.report",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Votes cast by other fact checking members",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_cast",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
