# Generated by Django 6.0 on 2025-12-14 13:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("factchecking", "0002_delete_source_alter_report_sources"),
        ("reportsources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Report",
            new_name="FactCheck",
        ),
    ]
