# Generated by Django 6.0 on 2025-12-14 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factchecking", "0003_rename_report_factcheck"),
        ("reportsources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factcheck",
            name="sources",
        ),
        migrations.RemoveField(
            model_name="factcheck",
            name="user",
        ),
        migrations.AddField(
            model_name="factcheck",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="User who created the report",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factcheck",
            name="factcheck_sources",
            field=models.ManyToManyField(
                help_text="Sources that support the fact check",
                related_name="factcheck_sources",
                to="reportsources.reportsource",
            ),
        ),
    ]
