# Generated by Django 5.2.6 on 2025-09-28 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_type', models.CharField(choices=[('Message', 'Message'), ('Follow', 'Follow'), ('Like', 'Like'), ('Donation', 'Donation'), ('Shoutout', 'Shoutout')], default='Follow', max_length=50)),
                ('read', models.BooleanField(default=False, help_text='Whether the user has read the notification')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User to notify', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PreferredNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_channel_activity', models.BooleanField(default=True)),
                ('video_recommendation', models.BooleanField(default=True)),
                ('channel_activity', models.BooleanField(default=True)),
                ('replies_activity', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('repost', models.BooleanField(default=True, help_text="When other users repost the user's content")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user',), name='one_notification_choice_per_user')],
            },
        ),
    ]
