# Generated by Django 4.1 on 2022-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='from_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='from_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
