# Generated by Django 3.1.1 on 2020-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_for',
            field=models.CharField(choices=[('Comment', 'Comment'), ('Video', 'Video'), ('Reply', 'Reply')], default='Video', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like', max_length=50),
        ),
    ]
