# Generated by Django 4.1 on 2022-08-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20201220_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_for',
            field=models.CharField(choices=[('Comment', 'Comment'), ('Video', 'Video'), ('Reply', 'Reply')], default='Video', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like', max_length=50),
        ),
    ]
