# Generated by Django 5.0.4 on 2024-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='active_accounts'),
        ),
    ]
