# Generated by Django 4.1.3 on 2022-11-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activationtoken_activationtoken_one_token_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activationtoken',
            name='one_token_per_user',
        ),
        migrations.AddConstraint(
            model_name='activationtoken',
            constraint=models.UniqueConstraint(fields=('token', 'myuser'), name='one_token_per_user'),
        ),
    ]
