# Generated by Django 4.1.3 on 2022-11-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_activationtoken_one_token_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
