# Generated by Django 4.1.3 on 2022-11-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_category_alter_report_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('SEXISM', 'Sexism'), ('Racism', 'Racism')], default='SEXISM', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='reference',
            field=models.CharField(default='fe538450664c92e69c54', max_length=100, unique=True),
        ),
    ]
