# Generated by Django 6.0 on 2025-12-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_notes", "0003_communitynotevote_reason"),
        ("reportsources", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommunityNoteSource",
        ),
        migrations.AlterField(
            model_name="communitynote",
            name="note_sources",
            field=models.ManyToManyField(
                help_text="Sources that support the note",
                related_name="notes",
                to="reportsources.reportsource",
            ),
        ),
    ]
