# Generated by Django 5.1.4 on 2025-03-25 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['created_on', '-pk'], 'verbose_name_plural': 'histories'},
        ),
    ]
