# Generated by Django 5.0.6 on 2024-10-18 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Unique reference for the view', max_length=100, unique=True)),
                ('duration', models.FloatField(default=0.0, help_text='The actual video duration')),
                ('ended_at', models.FloatField(default=0.0, help_text='The total duration viewed by the user')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(blank=True, help_text='View for a story', null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, help_text='View for a normal video', null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
    ]
