# Generated by Django 3.1.1 on 2020-12-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaview',
            name='reference',
            field=models.CharField(default='ce8817ad12', max_length=100),
        ),
    ]
