# Generated by Django 3.1.1 on 2020-12-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastats', '0002_auto_20201220_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaview',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
