# Generated by Django 4.1 on 2022-08-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastats', '0003_auto_20201220_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaview',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
