# Generated by Django 5.0.6 on 2024-10-18 21:57

import django.db.models.deletion
import donations.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mychannel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=5, validators=[donations.validators.donation_validator])),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('cancellation_asked', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mychannel.userchannel')),
            ],
        ),
    ]
