# Generated by Django 6.0.3 on 2026-03-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychannel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannel',
            name='category',
            field=models.CharField(choices=[('Beauty', 'Beauty'), ('Commentary', 'Commentary'), ('Corporate', 'Corporate'), ('Other', 'Other')], default='Beauty', max_length=100),
        ),
    ]
