# Generated by Django 6.0 on 2025-12-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factchecking", "0001_initial"),
        ("reportsources", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Source",
        ),
        migrations.AlterField(
            model_name="report",
            name="sources",
            field=models.ManyToManyField(
                related_name="reports", to="reportsources.reportsource"
            ),
        ),
    ]
