# Generated by Django 6.0 on 2025-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "factchecking",
            "0004_remove_factcheck_sources_remove_factcheck_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="factcheck",
            name="end_time",
            field=models.TimeField(
                default="00:00:00", help_text="End time of the fact check in the video"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factcheck",
            name="explanation",
            field=models.TextField(
                default="00:00:00", help_text="Explanation of the fact check"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factcheck",
            name="start_time",
            field=models.TimeField(
                default="00:00:00",
                help_text="Start time of the fact check in the video",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="factcheck",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Unique reference ID for the fact check",
                max_length=255,
                unique=True,
            ),
        ),
    ]
