import { library } from '@fortawesome/fontawesome-svg-core'
import { faThumbsDown as farThumbsDown, faThumbsUp as farThumbsUp } from '@fortawesome/free-regular-svg-icons'
import { faA, faArrowLeft, faArrowRight, faBars, faBell, faBellSlash, faBullhorn, faCaretDown, faChartSimple, faCircleCheck, faCog, faComment, faDollarSign, faDownload, faEllipsis, faEllipsisVertical, faFaceSmile, faGift, faHome, faList, faLock, faNoteSticky, faPause, faPen, faPlay, faPlus, faSave, faShare, faSort, faStar, faStop, faStore, faThumbsDown, faThumbsUp, faTrash, faTv, faUpload, faUser, faUserMinus, faVolumeHigh, faVolumeLow, faVolumeUp } from '@fortawesome/free-solid-svg-icons'


library.add(faA)
library.add(faBars)
library.add(faArrowRight)
library.add(faArrowLeft)
library.add(faBell)
library.add(faBellSlash)
library.add(faBullhorn)
library.add(faChartSimple)
library.add(faCaretDown)
library.add(faCircleCheck)
library.add(faComment)
library.add(faCog)
library.add(faDollarSign)
library.add(faDownload)
library.add(faEllipsis)
library.add(faEllipsisVertical)
library.add(faFaceSmile)
library.add(faGift)
library.add(faHome)
library.add(faLock)
library.add(faList)
library.add(faNoteSticky)
library.add(faPen)
library.add(faSort)
library.add(faUser)
library.add(faUpload)
library.add(faPlay)
library.add(faPlus)
library.add(faPause)
library.add(faSave)
library.add(faShare)
library.add(faStar)
library.add(faStop)
library.add(faStore)
library.add(faTv)
library.add(farThumbsUp)
library.add(farThumbsDown)
library.add(faThumbsUp)
library.add(faThumbsDown)
library.add((faTrash))
library.add(faUserMinus)
library.add(faVolumeHigh)
library.add(faVolumeLow)
library.add(faVolumeUp)
