# Generated by Django 5.1.4 on 2025-03-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_category_alter_report_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('SEXISM', 'Sexism'), ('Racism', 'Racism')], default='SEXISM', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='reference',
            field=models.CharField(default='8946baa7d064f6139ff0', max_length=100, unique=True),
        ),
    ]
