# Generated by Django 4.1.3 on 2024-03-11 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_channel_activity', models.BooleanField(default=True)),
                ('video_recommendation', models.BooleanField(default=True)),
                ('channel_activity', models.BooleanField(default=True)),
                ('replies_activity', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('repost', models.BooleanField(default=True, help_text="When other users repost the user's content")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Message', 'Message'), ('Follow', 'Follow'), ('Like', 'Like'), ('Donation', 'Donation'), ('Shoutout', 'Shoutout')], default='Follow', max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User to notify', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'ordering': ['-created_on', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='preferrednotification',
            constraint=models.UniqueConstraint(fields=('user',), name='one_notification_choice_per_user'),
        ),
    ]
